---
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - test/dummy/bin
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Exclude:
    - test/dummy/config/environments/development.rb
    - test/dummy/config/environments/production.rb
    - test/dummy/config/environments/test.rb

Style/Documentation:
  Enabled: false
