---
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  Exclude:
    - spec/dummy/bin
    - spec/dummy/db/schema.rb
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %> # Is a way to not run rubocop on git ignored file.
    - '<%= path.sub(/^!! /, '').strip %>'
    - '<%= path.sub(/^!! /, '').strip %>**/*'
  <% end %>
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Exclude:
    - spec/dummy/config/environments/development.rb
    - spec/dummy/config/environments/production.rb
    - spec/dummy/config/environments/test.rb

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - '**/*.erb_spec.rb'

Style/Documentation:
  Enabled: false
